apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-plugin-daemon
  namespace: dify
  labels:
    app: dify-plugin-daemon
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-plugin-daemon
  template:
    metadata:
      labels:
        app: dify-plugin-daemon
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      automountServiceAccountToken: false
      volumes:
      - name: dify-plugin-daemon-storage
        hostPath:
          path: /root/dify/app/plugin/storage
          type: DirectoryOrCreate
      containers:
      - name: dify-plugin-daemon
        image: dify-plugin:local
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
          protocol: TCP
          name: debug-port

        - containerPort: 5002
          protocol: TCP
          name: service-port
        envFrom:
        - secretRef:
            name: dify-secrets
        env:
        - name: REDIS_HOST
          value: dify-redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_USERNAME
          value: ""
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: REDIS_PASSWORD
        - name: REDIS_URL
          value: redis://:@dify-redis:6379/1

        - name: CELERY_BROKER_URL
          value: >-
            redis://$(REDIS_USERNAME):$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1
        - name: 'DB_DATABASE'
          # value: 'dify_plugin'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: DB_PLUGIN_DATABASE
        - name: 'SERVER_PORT'
          # value: '5002'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DAEMON_PORT
        # - name: 'EXPOSE_PLUGIN_DAEMON_PORT'
        #   value: '5002'
        - name: 'SERVER_KEY'
          # value: 'lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DAEMON_KEY
        - name: 'MAX_PLUGIN_PACKAGE_SIZE'
          # value: '52428800'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_MAX_PACKAGE_SIZE
        - name: 'PPROF_ENABLED'
          # value: 'false'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_PPROF_ENABLED
        - name: 'DIFY_INNER_API_URL'
          # value: 'http://dify-api:5001'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DIFY_INNER_API_URL
        - name: 'DIFY_INNER_API_KEY'
          # value: 'QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DIFY_INNER_API_KEY
        - name: 'PLUGIN_REMOTE_INSTALLING_HOST'
          # value: '0.0.0.0'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DEBUGGING_HOST
        - name: 'PLUGIN_REMOTE_INSTALLING_PORT'
          # value: '5003'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_DEBUGGING_PORT
        - name: 'PLUGIN_WORKING_PATH'
          # value: '/app/storage/cwd'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_WORKING_PATH
        - name: 'FORCE_VERIFYING_SIGNATURE'
          # value: 'true'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: FORCE_VERIFYING_SIGNATURE
        # - name: 'EXPOSE_PLUGIN_DEBUGGING_HOST'
        #   value: 'localhost'

        # - name: 'EXPOSE_PLUGIN_DEBUGGING_PORT'
        #   value: '5003'

        - name: 'PYTHON_ENV_INIT_TIMEOUT'
          # value: '120'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_PYTHON_ENV_INIT_TIMEOUT
        - name: 'PLUGIN_MAX_EXECUTION_TIMEOUT'
          # value: '600'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PLUGIN_MAX_EXECUTION_TIMEOUT
        - name: 'PIP_MIRROR_URL'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: PIP_MIRROR_URL
        # - name: 'ENDPOINT_URL_TEMPLATE'
        #   value: 'http://localhost/e/{hook_id}'
        volumeMounts:
        - name: dify-plugin-daemon-storage
          mountPath: /app/storage
---
apiVersion: v1
kind: Service
metadata:
  name: dify-plugin-daemon
  namespace: dify
spec:
  type: ClusterIP
  selector:
    app: dify-plugin-daemon
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: debug-port
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: service-port