apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-sandbox-config
  namespace: dify
data:
  config.yaml: |
    app:
      port: 8194
      debug: True
      key: dify-sandbox
    max_workers: 4
    max_requests: 50
    worker_timeout: 5
    python_path: /usr/local/bin/python3
    enable_network: True # please make sure there is no network risk in your environment
    allowed_syscalls: # please leave it empty if you have no idea how seccomp works
    proxy:
      socks5: ''
      http: ''
      https: ''
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-sandbox-dependencies
  namespace: dify
data:
  python-requirements.txt: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-sandbox
  namespace: dify
  labels:
    app: dify-sandbox
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-sandbox
  template:
    metadata:
      labels:
        app: dify-sandbox
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: dify-sandbox
        image: langgenius/dify-sandbox:0.2.11
        env:
        - name: API_KEY
          # value: "dify-sandbox"
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: SANDBOX_API_KEY
        - name: GIN_MODE
          # value: "release"
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: SANDBOX_GIN_MODE
        - name: WORKER_TIMEOUT
          # value: "15"
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: SANDBOX_WORKER_TIMEOUT
        - name: ENABLE_NETWORK
          # value: "true"
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: SANDBOX_ENABLE_NETWORK
        - name: SANDBOX_PORT
          # value: "8194"
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: SANDBOX_PORT
          # uncomment if you want to use proxy
        - name: HTTP_PROXY
          # value: 'http://dify-ssrf:3128'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: SANDBOX_HTTP_PROXY
        - name: HTTPS_PROXY
          # value: 'http://dify-ssrf:3128'
          valueFrom:
            secretKeyRef:
              name: dify-secrets
              key: SANDBOX_HTTPS_PROXY
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - "curl"
            - "-f"
            - "http://localhost:8194/health"
        ports:
        - containerPort: 8194
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dify-sandbox-dependencies
          mountPath: /dependencies
        - name: dify-sandbox-config
          mountPath: /conf
      volumes:
      - name: dify-sandbox-dependencies
        configMap:
          name: dify-sandbox-dependencies
      - name: dify-sandbox-config
        configMap:
          name: dify-sandbox-config
---
apiVersion: v1
kind: Service
metadata:
  name: dify-sandbox
  namespace: dify
spec:
  ports:
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: dify-sandbox
  type: ClusterIP
  clusterIP: None
  selector:
    app: dify-sandbox