apiVersion: v1
kind: Secret
metadata:
  name: dify-secrets
type: Opaque
stringData:
  SECRET_KEY: "sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U"
  DATABASE_URL: "postgresql://dify:dify@db:5432/dify"
  REDIS_HOST: "dify-redis"
  REDIS_URL: "redis://redis:6379/0"
  SANDBOX_API_KEY: "dify-sandbox"
  CONSOLE_API_URL: "http://localhost:8008/api"
  CONSOLE_WEB_URL: "http://localhost:8008"
  SERVICE_API_URL: "http://localhost:8008/v1"
  APP_API_URL: "http://localhost:8008/v1"
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  FLASK_DEBUG: "false"
  DEPLOY_ENV: "PRODUCTION"
  MIGRATION_ENABLED: "true"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  GUNICORN_TIMEOUT: "360"
  CELERY_BROKER_URL: "redis://:difyai123456@redis:6379/1"
  BROKER_USE_SSL: "false"
  CELERY_USE_SENTINEL: "false"
  CHECK_UPDATE_URL: "https://updates.dify.ai"
  OPENAI_API_BASE: "https://api.openai.com/v1"
  APP_WEB_URL: ''
  FILES_URL: ''
  LOG_FILE: /app/logs/server.log
  LOG_FILE_MAX_SIZE: '20'
  LOG_FILE_BACKUP_COUNT: '5'
  LOG_DATEFORMAT: '%Y-%m-%d %H:%M:%S'
  LOG_TZ: UTC
  INIT_PASSWORD: password
  FILES_ACCESS_TIMEOUT: '300'
  REFRESH_TOKEN_EXPIRE_DAYS: '30'
  APP_MAX_ACTIVE_REQUESTS: '0'
  APP_MAX_EXECUTION_TIME: '1200'
  DIFY_BIND_ADDRESS: '0.0.0.0'
  DIFY_PORT: '5001'
  SERVER_WORKER_AMOUNT: '1'
  SERVER_WORKER_CLASS: gevent
  SERVER_WORKER_CONNECTIONS: '10'
  CELERY_WORKER_CLASS: ''
  CELERY_WORKER_AMOUNT: ''
  CELERY_AUTO_SCALE: 'false'
  CELERY_MAX_WORKERS: ''
  CELERY_MIN_WORKERS: ''
  API_TOOL_DEFAULT_CONNECT_TIMEOUT: '10'
  API_TOOL_DEFAULT_READ_TIMEOUT: '60'
  ENABLE_WEBSITE_JINAREADER: 'true'
  ENABLE_WEBSITE_FIRECRAWL: 'true'
  ENABLE_WEBSITE_WATERCRAWL: 'true'
  DB_USERNAME: postgres
  DB_PASSWORD: difyai123456
  DB_HOST: dify-postgres
  DB_PORT: '5432'
  DB_DATABASE: dify
  SQLALCHEMY_POOL_SIZE: '30'
  SQLALCHEMY_POOL_RECYCLE: '3600'
  SQLALCHEMY_ECHO: 'false'
  POSTGRES_MAX_CONNECTIONS: '100'
  POSTGRES_SHARED_BUFFERS: 128MB
  POSTGRES_WORK_MEM: 4MB
  POSTGRES_MAINTENANCE_WORK_MEM: 64MB
  POSTGRES_EFFECTIVE_CACHE_SIZE: 4096MB
  REDIS_PORT: '6379'
  REDIS_USERNAME: ''
  REDIS_PASSWORD: difyai123456
  REDIS_USE_SSL: 'false'
  REDIS_DB: '0'
  REDIS_USE_SENTINEL: 'false'
  REDIS_SENTINELS: ''
  REDIS_SENTINEL_SERVICE_NAME: ''
  REDIS_SENTINEL_USERNAME: ''
  REDIS_SENTINEL_PASSWORD: ''
  REDIS_SENTINEL_SOCKET_TIMEOUT: '0.1'
  REDIS_USE_CLUSTERS: 'false'
  REDIS_CLUSTERS: ''
  REDIS_CLUSTERS_PASSWORD: ''
  CELERY_SENTINEL_MASTER_NAME: ''
  CELERY_SENTINEL_SOCKET_TIMEOUT: '0.1'
  WEB_API_CORS_ALLOW_ORIGINS: '*'
  CONSOLE_CORS_ALLOW_ORIGINS: '*'
  STORAGE_TYPE: opendal
  # STORAGE_TYPE: s3
  OPENDAL_SCHEME: fs
  OPENDAL_FS_ROOT: storage
  VECTOR_STORE: weaviate
  WEAVIATE_ENDPOINT: 'http://$(WEAVIATE_HOST):$(WEAVIATE_PORT)'
  WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
  UPLOAD_FILE_SIZE_LIMIT: '15'
  UPLOAD_FILE_BATCH_LIMIT: '5'
  ETL_TYPE: dify
  SCARF_NO_ANALYTICS: 'true'
  PROMPT_GENERATION_MAX_TOKENS: '512'
  CODE_GENERATION_MAX_TOKENS: '1024'
  PLUGIN_BASED_TOKEN_COUNTING_ENABLED: 'false'
  MULTIMODAL_SEND_FORMAT: base64
  UPLOAD_IMAGE_FILE_SIZE_LIMIT: '10'
  UPLOAD_VIDEO_FILE_SIZE_LIMIT: '100'
  UPLOAD_AUDIO_FILE_SIZE_LIMIT: '50'
  SENTRY_DSN: ''
  API_SENTRY_DSN: ''
  API_SENTRY_TRACES_SAMPLE_RATE: '1.0'
  API_SENTRY_PROFILES_SAMPLE_RATE: '1.0'
  WEB_SENTRY_DSN: ''
  INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: '4000'
  INVITE_EXPIRY_HOURS: '72'
  RESET_PASSWORD_TOKEN_EXPIRY_MINUTES: '5'
  CODE_EXECUTION_ENDPOINT: http://dify-sandbox:8194
  CODE_EXECUTION_API_KEY: dify-sandbox
  CODE_MAX_NUMBER: '9223372036854776000'
  CODE_MIN_NUMBER: '-9223372036854776000'
  CODE_MAX_DEPTH: '5'
  CODE_MAX_PRECISION: '20'
  CODE_MAX_STRING_LENGTH: '80000'
  CODE_MAX_STRING_ARRAY_LENGTH: '30'
  CODE_MAX_OBJECT_ARRAY_LENGTH: '30'
  CODE_MAX_NUMBER_ARRAY_LENGTH: '1000'
  CODE_EXECUTION_CONNECT_TIMEOUT: '10'
  CODE_EXECUTION_READ_TIMEOUT: '60'
  CODE_EXECUTION_WRITE_TIMEOUT: '10'
  TEMPLATE_TRANSFORM_MAX_LENGTH: '80000'
  WORKFLOW_MAX_EXECUTION_STEPS: '500'
  WORKFLOW_MAX_EXECUTION_TIME: '1200'
  WORKFLOW_CALL_MAX_DEPTH: '5'
  MAX_VARIABLE_SIZE: '204800'
  WORKFLOW_PARALLEL_DEPTH_LIMIT: '3'
  WORKFLOW_FILE_UPLOAD_LIMIT: '10'
  HTTP_REQUEST_NODE_MAX_BINARY_SIZE: '10485760'
  HTTP_REQUEST_NODE_MAX_TEXT_SIZE: '1048576'
  HTTP_REQUEST_NODE_SSL_VERIFY: 'true'
  SSRF_PROXY_HTTP_URL: 'http://dify-ssrf:3128'
  SSRF_PROXY_HTTPS_URL: 'http://dify-ssrf:3128'
  LOOP_NODE_MAX_COUNT: '100'
  MAX_TOOLS_NUM: '10'
  MAX_PARALLEL_LIMIT: '10'
  MAX_ITERATIONS_NUM: '5'
  TEXT_GENERATION_TIMEOUT_MS: '60000'
  PGUSER: postgres
  POSTGRES_PASSWORD: difyai123456
  POSTGRES_DB: dify
  PGDATA: /var/lib/postgresql/data/pgdata
  SANDBOX_GIN_MODE: release
  SANDBOX_WORKER_TIMEOUT: '15'
  SANDBOX_ENABLE_NETWORK: 'true'
  SANDBOX_HTTP_PROXY: 'http://dify-ssrf:3128'
  SANDBOX_HTTPS_PROXY: 'http://dify-ssrf:3128'
  SANDBOX_PORT: '8194'
  WEAVIATE_PERSISTENCE_DATA_PATH: /var/lib/weaviate
  WEAVIATE_QUERY_DEFAULTS_LIMIT: '25'
  WEAVIATE_AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
  WEAVIATE_DEFAULT_VECTORIZER_MODULE: none
  WEAVIATE_CLUSTER_HOSTNAME: node1
  WEAVIATE_AUTHENTICATION_APIKEY_ENABLED: 'true'
  WEAVIATE_AUTHENTICATION_APIKEY_ALLOWED_KEYS: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
  WEAVIATE_AUTHENTICATION_APIKEY_USERS: hello@dify.ai
  WEAVIATE_AUTHORIZATION_ADMINLIST_ENABLED: 'true'
  WEAVIATE_AUTHORIZATION_ADMINLIST_USERS: hello@dify.ai
  SSRF_HTTP_PORT: '3128'
  SSRF_COREDUMP_DIR: /var/spool/squid
  SSRF_REVERSE_PROXY_PORT: '8194'
  SSRF_SANDBOX_HOST: dify-sandbox
  SSRF_DEFAULT_TIME_OUT: '5'
  SSRF_DEFAULT_CONNECT_TIME_OUT: '5'
  SSRF_DEFAULT_READ_TIME_OUT: '5'
  SSRF_DEFAULT_WRITE_TIME_OUT: '5'
  POSITION_TOOL_PINS: ''
  POSITION_TOOL_INCLUDES: ''
  POSITION_TOOL_EXCLUDES: ''
  POSITION_PROVIDER_PINS: ''
  POSITION_PROVIDER_INCLUDES: ''
  POSITION_PROVIDER_EXCLUDES: ''
  CSP_WHITELIST: ''
  MAX_SUBMIT_COUNT: '100'
  TOP_K_MAX_VALUE: '10'
  DB_PLUGIN_DATABASE: dify_plugin
  EXPOSE_PLUGIN_DAEMON_PORT: '5002'
  PLUGIN_DAEMON_PORT: '5002'
  PLUGIN_DAEMON_KEY: lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi
  PLUGIN_DAEMON_URL: http://dify-plugin-daemon:5002
  PLUGIN_MAX_PACKAGE_SIZE: '52428800'
  PLUGIN_PPROF_ENABLED: 'false'
  PLUGIN_DEBUGGING_HOST: '0.0.0.0'
  PLUGIN_DEBUGGING_PORT: '5003'
  EXPOSE_PLUGIN_DEBUGGING_HOST: dify-plugin-daemon
  EXPOSE_PLUGIN_DEBUGGING_PORT: '5003'
  PLUGIN_DIFY_INNER_API_KEY: QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1
  PLUGIN_DIFY_INNER_API_URL: http://dify-api:5001
  ENDPOINT_URL_TEMPLATE: 'http://localhost/e/{hook_id}'
  MARKETPLACE_ENABLED: 'true'
  MARKETPLACE_API_URL: https://marketplace.dify.ai
  FORCE_VERIFYING_SIGNATURE: 'true'
  PLUGIN_PYTHON_ENV_INIT_TIMEOUT: '120'
  PLUGIN_MAX_EXECUTION_TIMEOUT: '600'
  PIP_MIRROR_URL: ''
  PLUGIN_STORAGE_TYPE: local
  PLUGIN_STORAGE_LOCAL_ROOT: /app/storage
  PLUGIN_WORKING_PATH: /app/storage/cwd
  PLUGIN_INSTALLED_PATH: plugin
  PLUGIN_PACKAGE_CACHE_PATH: plugin_packages
  PLUGIN_MEDIA_CACHE_PATH: assets
  ENABLE_OTEL: 'false'
  # Base64 encoded postgres username, default is postgres
  pg-username: cG9zdGdyZXM=
  # Base64 encoded postgres password, default is difyai123456
  pg-password: ZGlmeWFpMTIzNDU2
  # Base64 encoded postgres host, default is dify-postgres
  pg-host: ZGlmeS1wb3N0Z3Jlcw==
  # Base64 encoded postgres port 5432
  pg-port: NTQzMg==
  # Base64 encoded redis username, default is empty
  redis-username: ''
  # Base64 encoded redis password, default is difyai123456
  redis-password: ZGlmeWFpMTIzNDU2
  # Base64 encoded redis host, default is dify-redis
  redis-host: ZGlmeS1yZWRpcw==
  # Base64 encoded redis port 6379
  redis-port: NjM3OQ==
  # Base64 encoded weaviate host, default is dify-weaviate
  weaviate-host: ZGlmeS13ZWF2aWF0ZQ==
  # Base64 encoded weaviate port 8080
  weaviate-port: ODA4MA==